name: Greet first-time contributors

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the community.'
        pr-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the community.'
        footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/up4JGVbZ8G">Discord Server</a> and our <a href="https://chat.whatsapp.com/CVrBjAtYqxs6d7GFqZmhrR">WhatsApp Group</a> - we help and encourage each other to contribute to open source little . Any questions let us know.'
